### ISSUE TITLE
Alc Glitch before for credit check

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#102]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Nick Stefan | nick.stefan@palmetto.com | Getting the "whoops, looks like something went wrong" glitch when clicking the "credit check" button to send out new docs. | https://alchemy.palmetto.com/finance/creditcheckresults/xaqk | Low | No | Uhhhh...not sure |

**Comment by Kermit6868** [comment]
@ccoddington please take a look at this when you can.

**Comment by BhargavRentala** [comment]
Fixed
