### ISSUE TITLE
Update Tokens and Keys for Palmetto SB

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#105]

**Comment by BhargavRentala** [comment]
@ccoddington  Can you change the env file ?


Cosumer: 3MVG9sG9Z3Q1Rlbebp5CISYDJcZGlKD8FL1ngFv5sseU5VWatEn.ZrLf_Qk9Isu_yZ3Ncoksjer_bE1VTZGnX

Secret: 2346162468279789322
Security token (case-sensitive): IzLruHwuUsoj68VQag5SKzfc

**Comment by ccoddington** [comment]
UAT updated.
