### ISSUE TITLE
Error Launch Loan

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#143]
test:
https://alchemy-uat.palmetto.com/finance/creditcheckresults/pQRm
create opp
build system
select  subprime loan pal option
generate one proposal
run credit for loan pal
select the approved product and hit continue
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/7385ad83-1cba-435b-94e8-84c48364f6ac)

clicking on continue will navigate the user to DMC page. For some reason, that's not happening and the  function that creates a loan application in DocuSign is failing

**Comment by BhargavRentala** [comment]
refer to #78 and #21  if needs more context

**Comment by Kermit6868** [comment]
@ccoddington Can you estimate how much longer this ticket is going to take?

**Comment by BhargavRentala** [comment]
logs: https://alchemy-uat.palmetto.com/admin/logs

the error is in DMC service
Class:DMCService {"Function":"updateloanpalpushdata","Line No":528,"Message":"Api Response","Data":{"status":true,"code":1,"message":"Success","result":{"updatedAt":"2019-11-27T16:02:00.933Z","createdAt":"2019-11-27T16:01:15.608Z","application":{"applicant":{"address":{"zip":"29605","state":"SC","city":"Greenville","street":"43 Blake Street"},"annualIncome":"120000","dob":"1943-01-28","electronicConsent":true,"email":"HASKELL@mailinator.com","firstName":"JOANNE","lastName":"HASKELL","phone":"8432441212","spokenLanguage":"english","ssn":"***-**-7545"},"batteryIncluded":true,"isOccupant":true,"isOwner":true,"itcPct":"0.26","loanOption":null,"overrideResponse":{"Bucket":"sandbox-core.loanpal.com","Key":"application-responses/Solar/Approve100k"},"productType":"Solar","referenceNumber":"Loan-Application-6772_14399","salesRep":{"firstName":"Michael","lastName":"Epps","email":"michael.epps@palmetto.com"},"selectedLoanOption":"4","totalSystemCost":"$20,000.00"},"id":"19-13-000389","outcome":{"isSub650":false,"referenceNumber":"Loan-Application-6772_14399","maxLoanAmount":"100000","correlationId":"OverrideResponseNoId","type":"Single","totalSystemCost":"$20,000.00","loanId":"19-13-000389","status":"Approved","loanOptions":{"term":"20","isSub650":true,"id":"8","programFee":27.99,"rate":"5.99"},"stipulations":[]},"loanStatus":{"application":"Approved","approvedAt":"2019-11-27T16:01:16.383Z","creditExpiresAt":"2020-05-26T06:59:59.999Z","docsRequestedAt":"2019-11-27T16:01:48.204Z","docsSentAt":"2019-11-27T16:02:00.933Z","docsSubmittedAt":"2019-11-27T16:02:01.240Z","isSub650":false,"systemVerifiedAt":"2019-11-27T16:01:47.543Z"},"clientId":"PalmettoSolar","fundingConfig":{"milestones":{"1":{"netProgramFee":true,"fundingPct":100,"invoice":false}}}}}}

**Comment by BhargavRentala** [comment]
Class:TrackingApiController {"Function":"createLoanApplication","Line No":1404,"Message":"Try catch error.","Data":"#0 /var/www/20191119-153916/app/Http/Controllers/Api/TrackingApiController.php(1332): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'A non-numeric v...', '/var/www/201911...', 1332, Array)
