### ISSUE TITLE
Whitelist IP Addresses so BIA Team can access Alchemy

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#145]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| David Darden | david.darden@bigfishgames.com | We are setting up a new cloud based ETL tool (Rivery.io) to extract data from Alchemy.  We need the 52.14.86.20 , 13.58.140.165 and 52.14.192.86 IP addresses whitelisted.  This is a pilot to validate the tool so I can use my personal account. | https://riveryhelp.zendesk.com/hc/en-us/articles/360012543771-PostgreSQL-Walkthrough | Blocker | Small Group of Users | N/A |

**Comment by ddarden-palmetto** [comment]
We're going to be testing Stitch Data as well.  Can you whitelist 52.23.137.21/32, 52.204.223.208/32, 52.204.228.32/32 and 52.204.230.227/32 as well for that service?

**Comment by ccoddington** [comment]
RDS access (Port 5432) granted.
