### ISSUE TITLE
pdf proposal has a 30% ITC FAQ on it causing homeowner confusion 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#159]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| ac | andrew.catapano@palmetto.com | pdf proposal has a 30% ITC FAQ on it causing homeowner confusion. Verbiage on the pdf should reflect 26%  | https://alchemy.palmetto.com/dashboard | Low | Small Group of Users | all proposals  |

**Comment by Sean-Hayes124** [comment]
Problem resolved with card #240, prioritized above this currently.
