### ISSUE TITLE
Update NPS-Salesforce Integration

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#180]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Clint Cutchins | clint.cutchins@palmetto.com | Currently, there are only 3 NPS-related fields on a Contact in Salesforce (NPS Score, NPS Comment, NPS Type). It seems that if someone leaves an NPS review at point of sale, then another one at PTO, the "point of sale" NPS score will get overwritten in SF. So, I am asking for the 3 fields to be turned into 8 fields (the "NPS Type" field is unnecessary since it can be derived from the NPS Score):
 
Sales Rep NPS Score
Sales Rep NPS Comment

Install NPS Score
Install NPS Comment

PTO NPS Score
PTO NPS Comment

General NPS Score
General NPS Comment | https://na90.salesforce.com/0032L000018TKIo | Medium | Small Group of Users | N/A |

**Comment by BhargavRentala** [comment]
@ccutchins-palmetto  These are standard fields from NPS, I cannot push data to custom fields. The only possible solution here is to set field history tracking.

**Comment by ccutchins-palmetto** [comment]
Got it. Let's turn on field history tracking in that case. Does this mean
there is no way to get a "NPS Segment" field either (which would show if
the review was for the sales rep, install, or PTO)?

**Comment by BhargavRentala** [comment]
@ccutchins-palmetto Correct. We are not getting a segment name of the survey. There is an email alert sent to a contact based on the segments, I dont know if that will help you. 

Tracking is set for all the NPS fields on SF contact object.
