### ISSUE TITLE
IL Proposals Ignoring Incentive 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#197]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Kenneth DiLillo | kdillilo34@gmail.com | Presently IL proposals are not taking into account the SREC incentive amount in the pricing section for systems larger than 12kW. 

When you view this section you can see only the Federal tax credit is taken into account, not the SREC. 

I don't see a section to upload a doc so you can find this in the trello card (68).  | https://alchemy.palmetto.com/proposal/list/P6vR | Medium | No | 1) Rep requests design over 12kw
2) Builds a proposal respectively with a finance option 
3) Views proposal with HO and notices the month 18+ amount does not go down with option 2 and only the Federal amount is within option 1 |

**Comment by BhargavRentala** [comment]
per Ty:

"It is not supposed to. Systems above 12kW, in theory, should have an inverter greater than 10kW, which is a different payout structure in the ABP program. It is paid over 5 years and we no longer are accepting design requests over 10kW AC. It requires a code change in Alchemy to change the 12kW to 13.5 kW DC if that is your request. The application is operating as designed."

**Comment by BhargavRentala** [comment]
@TyFrye  Please QA this and confirm with Kellen

**Comment by TyFrye** [comment]
@BhargavRentala All tests passed.  Please notify me when it is moved to production so I can create the new incentive plans after the change is pushed.
@kellengarnaas
