### ISSUE TITLE
(trello 126)Design Workflow EPIC- Overhaul - #69, #70, #71	

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#20]
Propose and establish a new workflow for design/redesign requests with collaboration from Rick and team.

**Comment by BhargavRentala** [comment]
Updated workflow with Rick's input.

https://drive.google.com/file/d/0B_kiV9g5x-fDS3BjenJhYndqaEhuaUpBZHRVTEg2LWdSekZB/view?usp=sharing

**Comment by garybasrapalmetto** [comment]
received short term fixes for Gen 1 and will break out tickets.

Assigning this ticket for Jared to review for long term plan as discussed on call.
