### ISSUE TITLE
Sunlight ACH Policy Update - SPIKE

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#206]
Review this email from sunlight  change made on 12/11/2019

**We could be getting a wrong product in the quote or in Loan docs from sunlight**

Hi Gary,

Sunlight’s pricing assumes a discounted APR (0.50% APR discount) if customer’s elect to make automated loan payments via Automated Clearing House (ACH) processing.

What's Changing?
Starting today, Sunlight will be enforcing a policy of not providing this discounted rate for customers that opt out of ACH payments or fail to submit the required banking information before system installation. Therefore, starting today, December 11th, if a borrower opts out of ACH payments because they prefer to pay by check or other manual methods, then the APR on their loan will increase by 0.50%. For example, a customer with a 3.99% APR would receive a rate increase to 4.49%. 
 
Regardless of whether the consumer opts into ACH pricing or not, there will be no change in the current Sunlight pricing for you, our channel partners. (See picture below)

Click to Learn More
KEY TAKEAWAYS
If customers opt in to ACH payments and provide their banking information before their system is installed, they will benefit from a 0.50% discount on their APR.
If customers do not provide valid banking information before their system is installed, they will receive a non-discounted APR (0.50% APR increase).
If customers opt in to ACH payments during signing and do not provide valid banking information Sunlight will contact the customer weekly by email with an option complete setting up their ACH account. If the banking information is provided to Sunlight before the system is installed, they will still receive the 0.50% discounted APR.
Customers can also call into the Sunlight support line at (888) 850-3359 and provide their banking information directly to a Sunlight representative. This option is only available until the system has been installed.
If the customer does not provide banking information by the time the system has been installed, then the customer may or may not be able to work with their lender (credit union or banking partner) directly to receive the discounted ACH pricing after setting up automated payments. It is up to the lender’s discretion to offer a discount if the banking information is provided after installation.
Any customer accounts created before December 11th will be grandfathered into the previous payment structure and will generate the previous loan agreement. If these accounts require a change order on or after December 11th, they will not be impacted by the new ACH pricing.

**Comment by TyFrye** [comment]
I talked with Kellen and conducted a follow up call with Ren Scott.  The impact is 100% on the customer and loan doc side.  There is no change to the current API.  We could change our base call to reflect the non-ACH rate if we choose.  I declined that option and Gen 1 will continue as is and will have no impact from the ACH changes.
Ty
