### ISSUE TITLE
 Sunnova Sync button(Trello 127)

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#22]
Poly reps and also tested in my personal IA account. Users cannot click Sunnova Sync button- the button is there, but nothing happens when clicking it

**Comment by BhargavRentala** [comment]
https://intercom.help/alchemysupport/en/articles/2605346-add-your-homeowner-to-sunnova-portal

https://intercom.help/alchemysupport/en/articles/2934202-sunnova-manual-workflow-process-backdoor-option

**Comment by kellengarnaas** [comment]
It appears that there are screens and functionality built out, however the actual API connection process is not functioning for whatever reason. Setting to an 8 for a deep dive into the issue, however it's entirely possible it goes quicker than that depending on the nature of the issue(s).

**Comment by kellengarnaas** [comment]
Mostly squared away from a code clean-up standpoint. Just waiting on @BhargavRentala to help square away Sunnova Salesforce API credentials for testing

**Comment by BhargavRentala** [comment]
sent an email to Jason at Sunnova and looped in Sean to expedite the process. Waiting on a response from them.

**Comment by BhargavRentala** [comment]
Hi Palmetto Team,

Here are the latest API credentials for our team to use:
 

PALMETTO

 

Staging Environment

 

API endpoints:

https://api.sunnova.com/v1/staging/partner

 

Partner Portal Login:

https://staging-sunnovaenergy.cs91.force.com/login

 

Consumer Key :

3MVG9d3kx8wbPieE1owJgtExii4lJi2S6HkRHOsYgLGvVzS8vaBDtJ44d3Th48SgBIC4p4k0fycNC0ltDefqK

 

Consumer Secret :

4DD79A0A1B193197591CC133474D80627F984ECDA22556A33AA54158E9AF92EE

 

Sandbox Callback URLs:

https://www.getpostman.com/oauth2/callback

https://70alchemy.palmetto.com/sunnovacallback

http://localhost:10131/sunnovacallback

https://12alchemy.palmetto.com/sunnovacallback

https://30alchemy.palmetto.com/sunnovacallback

https://60alchemy.palmetto.com/sunnovacallback

https://50alchemyperf.palmetto.com/sunnovacallback

 

Partner users for Testing:

 

Username : alchemy@palmetto.com.staging

Email: alchemy@palmetto.com

**Comment by kellengarnaas** [comment]
We are now up to date with functioning credentials for Sunnova API on the the UAT server. I've done some troubleshooting and a few bug fixes along the way.

Some of the test Opps work on UAT, and a few of them have issues, however I'm not sure if that is due to actual errors in the system or if I was simply testing Opps with incorrect or incomplete data. At this point if @BhargavRentala can run some tests on the UAT build, we can get some feedback and move along from there.

**Comment by kellengarnaas** [comment]
Seeing an issue occurring that appears to revolve around email addresses with special characters. Occasionally getting 'Something Went Wrong' errors when syncing with emails with '+'s and '.'s in them. Will need to investigate further to find the exact root cause of the issue.
