### ISSUE TITLE
SU access for Alchemy 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#235]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Allen griffith | allen.griffith@palmetto.com | Add Alchmey Admin access to users | https://alchemy.palmetto.com/goal/dashboard | Medium | Small Group of Users | With the new Pod structure we have several new Account Managers that will need full access rights to help their sales reps:

Ken Crabb, Alyssa Haley, Chris Graham, McKenna Beam, Allen Griffith  |

**Comment by kellengarnaas** [comment]
Ken Crabb, Alyssa Haley and Allen Griffith have all been granted Super Admin access to Alchemy.

@BhargavRentala: Chris Graham and McKenna Beam have multiple accounts in the system (Chris has 6, McKenna 3). Is there one account specific we'd like to grant Admin access to for those users, or should we grant admin access to all of these accounts?
