### ISSUE TITLE
Change IL rebate coding to allow Admin to create values in Market Manager

### ISSUE THREAD

**Issue by TyFrye** [palmetto-tech/Palmetto#239]
What will the effort be to remove the custom coding created for the IL rebates and allow the Market Manager to work as designed?

This will allow correcting the maximum kW size and removing the rebate for systems over 10kW AC.

**Comment by Sean-Hayes124** [comment]
This must happen ahead of the rebate step-down slated for March, 2020.

**Comment by TyFrye** [comment]
Completed and active in Alchemy
