### ISSUE TITLE
CSV export of Financing Products in Alchemy

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#258]

**Comment by kellengarnaas** [comment]
`Financing ID,term,apr,dealer_fee,isACH,type,years
sunlight_10_standard,120,2.99,13.0,true,standard,10
sunlight_12_standard,144,2.99,13.0,true,standard,12
sunlight_15_standard,180,3.99,13.0,true,standard,15
sunlight_20_standard,240,4.99,13.0,true,standard,20
sunlight_25_standard,300,4.99,17.0,true,standard,25
sunlight_15_subprime, 180, 7.99,20.5,true,subprime,15
loanpal_10,10,3.99,15.25,true,standard,10
loanpal_15,15,4.99,12.5,true,standard,15
loanpal_20_low,20,3.99,21.0,true,standard,20
loanpal_20_high,20,5.99,10.75,true,standard,20
loanpal_25_low,25,2.99,23.55,true,standard,25
loanpal_20_low_subprime,20,3.99,32,true,subprime,20
loanpal_20_high_subprime,20,5.99,30,true,subprime,20
loanpal_20_lower,20,2.99,22.5,true,standard,20
loanpal_10,10,3.99,15.25,true,standard,10
loanpal_15,15,4.99,12.5,true,standard,15
loanpal_20_low,20,3.99,21.0,true,standard,20
loanpal_20_high,20,5.99,10.75,true,standard,20
loanpal_25_low,25,2.99,23.55,true,standard,25
loanpal_20_low_subprime,20,3.99,32,true,subprime,20
loanpal_20_high_subprime,20,5.99,30,true,subprime,20
loanpal_20_lower,20,2.99,22.5,true,standard,20`
