### ISSUE TITLE
Duplicate HIC in DMC 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#260]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| JENNIFER HARPER | jenna.harp@yahoo.com | This homeowner appears to have to identical HIC contracts listed in their action required tab | https://alchemy.palmetto.com/contract/upload/documents/PNja | Medium | No | 1) Find HO in Alchemy
2) Go to DMC
3) Locate the action required tab and note to HICs |

**Comment by TyFrye** [comment]
Corrected.  Old HIC was left active when new HIC was activated.
