### ISSUE TITLE
Unable to progress to DMC(Trello228)

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#261]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Robert Zielinski | zobf37@gmail.com | Rep in home cannot progress past the credit approval screen, for new LP product added | https://alchemy.palmetto.com/finance/creditcheckresults/JMAO | Blocker | Yes | Using the 25 year product added to the system by tech department |

**Comment by kellengarnaas** [comment]
The interface relies on hidden radio buttons to trigger the loan selection like the following:
`<input type="radio" id="sradio07" name="choicechoosel" value="3.99|loanpal_10|Loanpal" class="lon_10 lon_radio" onclick="updateSelectClass('lon_10')" disabled="true">`

For whatever reason it is not present on the page for Loanpal 25 Yr/2.99

Will dive in deeper to determine the issue

**Comment by BhargavRentala** [comment]
Hotfix in production did not fix the issue.
