### ISSUE TITLE
Roger Vann - LP Sub650 Not Live

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#268]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Roger Vann | rogervann47@yahoo.com | LP Sub650 Does Not Correctly Run | https://alchemy.palmetto.com/finance/creditcheckresults/Ln0a | Blocker | Yes | Correct workflow within Alchemy, just not showing correct credit approval |

**Comment by TyFrye** [comment]
Loanpal had not activated subprime in production.  The request is with their tech team and should take 24 hours or less.
