### ISSUE TITLE
SPIKE - Home App Consumption monitoring(Trello236)

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#271]

**Comment by kellengarnaas** [comment]
A handful of endpoints were commented out in the routes file in Laravel. The main services appear to be functioning now, although there are still a handful of 504 timeouts that should be resolved at some point. 

Additionally there is a general slowness to the app that is probably related to trying to load so many third-party services via jquery. It may be something to look into at some point, but is probably lower priority.,

**Comment by kellengarnaas** [comment]
Upon further investigation, I've found the following:
-Not all API endpoints time out, but the ones that do die after 60 seconds, which is the default timeout for apache
-The Home Dashboard is making over 30 API requests simultaneously just to load the dashboard, which seems like a lot to me just for one user to load one page
- Looking at the load on the machine during one load of the dashboard, the CPU numbers max completely out, so I think we're looking at a processor limit issue, which is causing the requests to take a super long time.

![Screen Shot 2020-01-14 at 2.19.00 PM.png](https://images.zenhubusercontent.com/5df12c4e80dbe847857ce21b/f0d44c97-308b-4f7b-93c6-f37ed44abb9d)

**Comment by BhargavRentala** [comment]
Lets upgrade to t2.xlarge @kellengarnaas
