### ISSUE TITLE
Unable to access opp in Alchemy

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#273]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Oswaldo Nieves | osana65@gmail.com | I am getting a whoops error trying to get into the opp in Alchemy, please open this up.  | https://na90.salesforce.com/0062L00000SWKW3?srPos=0&srKp=098 | High | No | 1) Click on Oswaldo Nieves 
2) Get to Whoops page. |

**Comment by kellengarnaas** [comment]
Not able to reproduce. When I click Oswaldo Nieves in the opportunities dashboard, I am directed to Opportunity pipeline as expected.

![Screen Shot 2020-01-15 at 2.53.29 PM.png](https://images.zenhubusercontent.com/5df12c4e80dbe847857ce21b/85b6dad5-48a4-421b-b00b-caec8606e98c)![Screen Shot 2020-01-15 at 2.53.36 PM.png](https://images.zenhubusercontent.com/5df12c4e80dbe847857ce21b/17555bab-8d21-4e74-bda7-bfe63f00b950)
