### ISSUE TITLE
remove additional products no longer offered in alchemy

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#307]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| ac | andrew.catapano@palmetto.com | we are pushing battery sales, and pointing reps to the + ADDITIONAL PRODUCTS drop down list when selecting pricing. However, there are items including energy monitoring, no longer offered, which must be removed from that list so that they cannot be selected/put on the HIC  | https://alchemy.palmetto.com/proposal/pricing-payment/4zmr/axRN/p5NB/3Bkw | Low | Yes | Build system design
click NEXT to view pricing and additional products dropdown option  |

**Comment by TyFrye** [comment]
No longer used products have been removed.
Tesla Powerwall 13.5kWh and Adder remain.
