### ISSUE TITLE
testing ticket from intercom

### ISSUE THREAD

**Issue by garybasrapalmetto** [palmetto-tech/Palmetto#41]
> test

**Link:** [Conversation with Michael Epps](https://app.intercom.com/a/apps/jbvixi6u/respond/inbox/all/conversations/24426733298)

**Customer:** [Michael Epps](https://app.intercom.com/a/apps/jbvixi6u/users/5afec9146e6da5af76d1c47b/all-conversations)
**Customer ID:** 6
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/jbvixi6u/respond/inbox/all/conversations/24426733298) when this issue is closed.

**Comment by BhargavRentala** [comment]
testastasrs
