### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#55]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Testy testerson | testy@test.com | Please let me know if this goes through. I might have place URLs here in description and the URL field below.  | https://app.slack.com/client/T23ANMAFK/GQCC5NDBQ/thread/GK4A6AM7X-1573153526.002300 | Low | No | 1) Dumb user looking to submit tickets properly 2) fixed |

**Comment by garybasrapalmetto** [comment]
got it Wes
