### ISSUE TITLE
Alchemy Impact on SF field Clean-up

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#57]
Review the redundant fields from Salesforce if they are integrated to any Alchemy service. I made sure there is no reference in the code. 

1. needed_to_close__c
2. ic_payment_rec_d_date__c
3. shade_on_roof__c
4. average_electrical_bill__c
5. x25_year_do_nothing_c__c
6. credit_650__c
7. referred_by_code__c
8. est_sales_volume__c
9. w_9_recieved_south_carolina__c
10. secondary_contact__c
11. utility_company__c
12. own_or_rent__c
13. ip_address__c
14. page_uuid__c
15. date_submitted__c
16. page_url__c
17. x25_year_do_nothing__c

**Comment by garybasrapalmetto** [comment]
@BhargavRentala none of these fields are in the code for alchemy.
