### ISSUE TITLE
Correct the format of the co-applicants State to match the primary applicant

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#64]
Email from LoanPal: 

Loan ID: 19-04-015672

Ref ID: Loan-Application-8357_18232

Applicant: Paulina Autiello

 

Can you please correct the format of the co-applicants State to match the primary applicant? 

"city": "Johnston",

       "state": "Rhode Island",

"zip": "02919"

Palmetto Team –

 

We are noticing that when Palmetto submits a loan with 2 borrowers via our API, the format of the State for the 2nd borrower is incorrect.  The State is spelled out instead of being submitted as a 2 character postal code.  Applications are still processing correctly but they have to be corrected on our side.

 

Can you change your create application API request when there are 2 borrowers so that it only submits the 2 character postal code for State?

 

I fixed these loans already:

19-01-014201

19-05-012687

19-05-014443

19-05-014594

19-06-014544

19-06-014715

19-07-014618

19-09-010453

19-11-012114

19-12-014460

19-16-014693

 

Thanks,

Steve

**Comment by kellengarnaas** [comment]
I have a fix in place, however I'm noticing on UAT that the co-borrower form is not loading correctly. @BhargavRentala is that an issue associated with UAT only, or is this an issue we should look into?

**Comment by BhargavRentala** [comment]
@kellengarnaas  I am not sure what you're referring to. Can you screen share and explain when you get a chance?
