### ISSUE TITLE
Need to have CP in Database

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#74]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Kenneth Bassett | kbassetthhi60@gmail.com | Per conversations with Bhargav, we need to move him to database - he's a CP that doesn't have much in salesforce to send out docusign templates / attach documents | https://na90.salesforce.com/_ui/search/ui/UnifiedSearchResults?searchType=2&sen=a1Q&sen=a1R&sen=a0z&sen=00O&sen=00Q&sen=001&sen=068&sen=003&sen=01t&sen=00T&sen=005&sen=500&sen=00U&sen=006&sen=701&str=kenneth+bassett | High | No | Not sure how he onboarded. Previously sold via a different CP and is now working with Palmetto selling direct |

**Comment by BhargavRentala** [comment]
@garybasrapalmetto  Change the ids to the following values

1. sf_contact 0032L000013hpiyQAA
2. sf acount 0012L00000wrpC3QAI
3. sf owner id 0051a000002WX3IAAW

**Comment by garybasrapalmetto** [comment]
@BhargavRentala done
