### ISSUE TITLE
Opp has been switched to sunlight and in the DMC it is not showing any financier. They signed and were approved for sunlight 12 yer.

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#75]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Alejandro Bastidas | albastidas@gmail.com | Opp has been switched to sunlight and in the DMC it is not showing any financier. They signed and were approved for sunlight 12 yer. | https://alchemy.palmetto.com/finance/creditcheckresults/lDYK | High | No | Normal work flow  |

**Comment by garybasrapalmetto** [comment]
hey Anthony, the loan is missing the sunlight credit id and sunlight quote id. If you can send those we can update it.
