### ISSUE TITLE
Credit Error? 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#77]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Kenneth Perez Rivera | kenepaperez01@gmail.com | CP alleging credit error when processing for SL. Can you please research and validate? 

I looked into the account in Alchemy and saw the credit was sitting on the "Run Credit" page as if rep did not process. I then checked SL and saw an approval made moments ago.  | https://slfportal.com/orange/#/creditloan | High | No | 1) Find HO in Alchemy and click on the credit tab, note that credit does not look to have been processed. 
2) Find the homeowner in SL and see credit had been processed. 
3) Both SSed if you would like to see. I Don't see a field to leave attachments with this ticket system. |

**Comment by garybasrapalmetto** [comment]
@ Wes, please provide the sunlight project id, sunlight applicant id, credit id, quote id and system id then we can manually sync this one for https://alchemy.palmetto.com/finance/creditcheck/N9OD

Also, this project looks like tons of changes in history so not related to credit check error.
