### ISSUE TITLE
Loanpal new products

### ISSUE THREAD

**Issue by garybasrapalmetto** [palmetto-tech/Palmetto#78]
environment: UAT
file: loanpal.php in config.

add the following after line 119:

'loanpal_25_low' => [
            "term"=> 25,
            "apr"=> 2.99,
            "isACH"=> true,
            'dealer_fee' => 23.55,
            'type' => 'standard',
            'years' => 25,
            'loanOption' => 6,
        ],

'loanpal_20_low_subprime' => [
            "term"=> 20,
            "apr"=>3.99,
            "isACH"=> true,
            'dealer_fee' => 32,
            'type' => 'subprime',
            'years' => 20,
            'loanOption' => 7,
        ],

'loanpal_20_high_subprime' => [
            "term"=> 20,
            "apr"=>5.99,
            "isACH"=> true,
            'dealer_fee' => 30,
            'type' => 'subprime',
            'years' => 20,
            'loanOption' => 8,
        ],

**Comment by ccoddington** [comment]
Deployed to UAT.

**Comment by garybasrapalmetto** [comment]
follow up changes to ContractService.php in app/Http/Services

1) Around line 697 we set the value for Financing_Tool__c to "Loan Pal" for SF.
- change it to look at the 'type' field in the previous change you made. If "standard" then send "Loan Pal" and if "subprime" then send "Loan Pal - SubPrime"

**Comment by garybasrapalmetto** [comment]
@ccoddington one more add to the loanpal.php:

'loanpal_20_lower' => [
            "term"=> 20,
            "apr"=> 2.99,
            "isACH"=> true,
            'dealer_fee' => 23.55,
            'type' => 'standard',
            'years' => 20,
            'loanOption' => 5,
        ],

**Comment by ccoddington** [comment]
Deployed to UAT.

**Comment by garybasrapalmetto** [comment]
@ccoddington need to copy the change for SF to another file

follow up changes to ApiController.php in app/Http/Controller/Api

1) Around line 2420 we set the value for Financing_Tool__c to "Loan Pal" for SF.

change it to look at the 'type' field in the previous change you made. If "standard" then send "Loan Pal" and if "subprime" then send "Loan Pal - SubPrime"

**Comment by ccoddington** [comment]
Deployed to UAT.

**Comment by garybasrapalmetto** [comment]
@ccoddington need to copy the change for SF to another file yet again

follow up changes to TrackingApiController.php in app/Http/Controller/Api

1) Around line 1328 & 1370 we set the value for Financing_Tool__c to "Loan Pal" for SF.

change it to look at the 'type' field in the previous change you made. If "standard" then send "Loan Pal" and if "subprime" then send "Loan Pal - SubPrime"

**Comment by ccoddington** [comment]
Deployed to UAT.

**Comment by BhargavRentala** [comment]
@ccoddington  can you change the dealer fee to 22.50?
UAT 
config/loanpal.php



'loanpal_20_lower' => [
            "term"=> 20,
            "apr"=> 2.99,
            "isACH"=> true,
            'dealer_fee' => 23.55, 
            'type' => 'standard',
            'years' => 20,
            'loanOption' => 5,

**Comment by BhargavRentala** [comment]
reference
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/6a367f7d-9721-428c-b104-43eaa6a2b7d0)

**Comment by ccoddington** [comment]
Deployed to UAT.

**Comment by BhargavRentala** [comment]
test1: 

1. Create an Opp from Sunlight hard pull test data
2. Select Sunlight standard product in financing Option(10yr 2.99)
3. generate proposal pdf
4. Launch credit for sunlight only
5. getting an error
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/adecc5e4-7b54-4210-a54b-90d87d82450b)
6. click OK. Navigate to other screen and select on Run credit check tab 
7. sunlight result is displayed here
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/eaedcd73-7aca-49ea-81c6-9e15af0d86df)
8. rerun credit 
9. launch Loanpal credit check. Project is approved for 20yr 5.99 but the generated proposal is for sunlight 10yr 2.99
10. select the approved loanpal product and click continue
11. user will be navigated to DMC
12. Click choose financing on the same opportunity
13. select loanpal subprime(20 yr 5.99)
14. generated loanpal proposal 
15. rerun credit for loanpal
Error screen
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/5e1c5ce6-9fba-4c4f-a3a0-b47a668d685b)

**Comment by BhargavRentala** [comment]
https://alchemy-uat.palmetto.com/finance/creditcheck/K0Xv/W09b

**Comment by BhargavRentala** [comment]
test2: 
https://alchemy-uat.palmetto.com/finance/creditcheckresults/dxYq

getting whoops error

**Comment by BhargavRentala** [comment]
test3: https://alchemy-uat.palmetto.com/finance/creditcheckresults/r9z9


Error launch loan when approved(loanpal) fianncier is selected to continue 
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/542e10d5-7827-4c90-9f43-5146e0579862)

**Comment by BhargavRentala** [comment]
test4: https://alchemy-uat.palmetto.com/solar-design/system-detail/view/kdja/LNln?tide=1

1. create an Opp
2. select one standard and one subprime for Loanpal
3. generate standard loanpal proposal
4. run credit 
5. success with result approved and navigated to dMC

**Comment by BhargavRentala** [comment]
test5: https://alchemy-uat.palmetto.com/solar-design/system-detail/view/pQRm


1. create opp
2. build system
3. select two subprime loanpal options
4. generate one proposal
5. run credit for loanpal
6. select the approved product and hit continue
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/ad091204-bfea-4ab8-80c1-b4787ad53ef8)

**Comment by BhargavRentala** [comment]
1. running sunlight is totally broken even a standard product is selected
2. selecting approved loan pal subprime product is causing an error to proceed to DMC
