### ISSUE TITLE
ERROR in DMC when sending NJ clean energy 1 2 3 palmetto

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#89]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| ac | andrew.catapano@palmetto.com | ERROR in DMC when sending NJ clean energy 1 2 3 palmetto | https://alchemy.palmetto.com/contract/upload/documents/a0VL | Medium | Yes | click send- creates ERROR pop up  |

**Comment by garybasrapalmetto** [comment]
@BhargavRentala what is the error? Unable to reporduce any.
