### ISSUE TITLE
CP sunergy receiving frequent credit check issues-- they are running credit but approvals are not reflecting on the credit check screen. I typically thought this might be beacuse they are calling into loanpal to overturn a decline, however, this recent case happened with SL 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#93]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| ac  | andrew.catapano@palmetto.com | Issata Oluwadare
Ran LP and SL credit 
Stipped by LP and SL both
However, no credit check results are showing in alchemy

Previously thought this issue might be stemming from them getting an approval outside of alchemy, by calling financier.

However, this case happened with sunlight as well.
 | https://alchemy.palmetto.com/finance/creditcheck/9QP6 | Medium | Small Group of Users | Issata Oluwadare
Ran LP and SL credit 
Stipped by LP and SL both
However, no credit check results are showing in alchemy

Previously thought this issue might be stemming from them getting an approval outside of alchemy, by calling financier.

However, this case happened with sunlight as well.
 |

**Comment by garybasrapalmetto** [comment]
I am seeing a LP approval.

**Comment by garybasrapalmetto** [comment]
@BhargavRentala please relay to AC
