### ISSUE TITLE
SR Inside Sales Mgr

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#95]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Allen | allen.griffith@palmetto.com | New Alchemy user having issue at address.  user email jaedwardssolar@gmail.com:    At customer detail panel,  user outs in information and never moves to the next step.  Only shows icon spinning.  This has been an issue for him for 2 weeks.  

Have used other steps to resolve,  hard refresh, log out back in, icognito login to no avail.  

Please advise: | http://alchemy.palmetto.com | Blocker | Small Group of Users | Have used other steps to resolve,  hard refresh, log out back in, icognito login to no avail.   |

**Comment by garybasrapalmetto** [comment]
spoke to Allen and requested user login to reproduce.

**Comment by BhargavRentala** [comment]
Allen reached out on Nov 15th about getting the CP's login info to troubleshoot
