### ISSUE TITLE
Access to VPN, Alchemy, Sales Force, etc.

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#96]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| David Darden | david.darden@palmetto.com | This is an access request for Cory Finnell, Charlie Moore, and David Darden.  Cory may already have access to some of these.  As new team members we need access to (in priority order) VPN (to access the Alchemy database), read access to the Alchemy database, access to Salesforce (both UI and API), access to Hubspot (both UI and API), access to the UAT environment for Gen 2, read access to the data store for the Gen 2 UAT environment, access to AWS, and access to Facebook Ads.  Please let me know what further details you need.  Apologies for the big request; please feel free to break this up (everything starting with the UAT isn't blocking us at this time). | http://www.palmetto.com | Blocker |  | N/A |

**Comment by ddarden-palmetto** [comment]
As of 2019-11-21 we have access to Salesforce, Hubspot, Facebook Ads, and the Gen 2 UAT environment.  

We need access to the VPN, Alchemy DB, Gen 2 DB, and AWS.  These are blocking our team from moving forward.

**Comment by ccoddington** [comment]
Credentials provided via Slack. Cory already had access via VPN and RDS so he received credentials for only Mongo.
